// <auto-generated />
using AOKMovieLibrary.Models.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AOKMovieLibrary.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20241219150320_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AOKMovieLibrary.Models.DAL.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<int>("Runtime")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("AOKMovieLibrary.Models.DAL.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Christopher",
                            Lastname = "Nolan"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Leonardo",
                            Lastname = "DiCaprio"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Joseph",
                            Lastname = "Gordon-Levitt"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Ellen",
                            Lastname = "Page"
                        },
                        new
                        {
                            Id = 5,
                            Firstname = "Lana",
                            Lastname = "Wachowski"
                        },
                        new
                        {
                            Id = 6,
                            Firstname = "Keanu",
                            Lastname = "Reeves"
                        },
                        new
                        {
                            Id = 7,
                            Firstname = "Laurence",
                            Lastname = "Fishburne"
                        },
                        new
                        {
                            Id = 8,
                            Firstname = "Carrie-Anne",
                            Lastname = "Moss"
                        },
                        new
                        {
                            Id = 9,
                            Firstname = "Francis",
                            Lastname = "Coppola"
                        },
                        new
                        {
                            Id = 10,
                            Firstname = "Marlon",
                            Lastname = "Brando"
                        },
                        new
                        {
                            Id = 11,
                            Firstname = "Al",
                            Lastname = "Pacino"
                        },
                        new
                        {
                            Id = 12,
                            Firstname = "James",
                            Lastname = "Caan"
                        },
                        new
                        {
                            Id = 13,
                            Firstname = "Quentin",
                            Lastname = "Tarantino"
                        },
                        new
                        {
                            Id = 14,
                            Firstname = "John",
                            Lastname = "Travolta"
                        },
                        new
                        {
                            Id = 15,
                            Firstname = "Uma",
                            Lastname = "Thurman"
                        },
                        new
                        {
                            Id = 16,
                            Firstname = "Samuel",
                            Lastname = "Jackson"
                        },
                        new
                        {
                            Id = 17,
                            Firstname = "Frank",
                            Lastname = "Darabont"
                        },
                        new
                        {
                            Id = 18,
                            Firstname = "Tim",
                            Lastname = "Robbins"
                        },
                        new
                        {
                            Id = 19,
                            Firstname = "Morgan",
                            Lastname = "Freeman"
                        },
                        new
                        {
                            Id = 20,
                            Firstname = "Bob",
                            Lastname = "Gunton"
                        });
                });

            modelBuilder.Entity("MoviePerson", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors", (string)null);
                });

            modelBuilder.Entity("AOKMovieLibrary.Models.DAL.Movie", b =>
                {
                    b.HasOne("AOKMovieLibrary.Models.DAL.Person", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MoviePerson", b =>
                {
                    b.HasOne("AOKMovieLibrary.Models.DAL.Person", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AOKMovieLibrary.Models.DAL.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
